### ISSUE TITLE
Why is the "test3" site (path to IdenTrust) still valid in my browsers?

### ISSUE THREAD

**Issue by grandamp** [18F/fpki-testing#2]
[The certificate from IdenTrust to the FBCA was revoked on February 17th](https://bugzilla.mozilla.org/show_bug.cgi?id=1037590#c27), yet this certificate path remains valid through Mozilla Firefox:

![image](https://cloud.githubusercontent.com/assets/13126304/13198066/d90ec6c0-d7cc-11e5-8685-ef68971aac4d.png)

As well as Chrome 48.0.2564.95 on Android 6.0.1:

![image](https://cloud.githubusercontent.com/assets/13126304/13198091/a9be9142-d7cd-11e5-8008-7689a88b6f3d.png)

**Comment by konklone** [comment]
I was wondering the same thing. @rmhrisk showed me this link which tries to trace revocation information through the whole chain:

https://certificate.revocationcheck.com/test3.fpki.18f.gov

Chrome [doesn't use OCSP for revocation checking](https://www.imperialviolet.org/2011/03/18/revocation.html) (even [today](https://www.imperialviolet.org/2014/04/29/revocationagain.html)), so I understand that. They do use CRL, and I believe OCSP stapling, but I'm not stapling revocation at test3 (I should add this), and CRL sets take time to get distributed.

Firefox does check revocation though, and I'm not sure why I'm not seeing an impact yet.

**Comment by grandamp** [comment]
Pretty cool web site, though it claimed it could not download '
http://pki.treas.gov/OCIO_CA4.crl', I'm able to get it just fine.  A pretty
print of the OCSP response would be helpful in this case. (For the error:
Signature error on Identrust OCSP response)

SSLLabs was showing this error prior to the revocation:
https://www.ssllabs.com/ssltest/analyze.html?d=test3.fpki.18f.gov&latest

**Comment by konklone** [comment]
Yes, SSL Labs shows the certificate as `REVOKED`, while also showing errors validating OCSP responses to two of Identrust's OSCP responders. 

I assume it has something to do with the fact that Identrust's OCSP responders use HTTPS (which seems unusual for OCSP), but I can make a request from cURL (on Ubuntu, using a vanilla Mozilla root store) to both of them just fine:

```
$ curl --head https://publicsector.ocsp.identrust.com
HTTP/1.1 200 OK

$ curl --head https://aces.ocsp.identrust.com
HTTP/1.1 200 OK
```

Perhaps the Java root store being used by SSL Labs (and maybe certificate.revocationcheck.com?) don't have the root certificate Identrust's OCSP responder chains to.

An `openssl s_client` command to both OCSP responders shows the same intermediates and roots:

```
Certificate chain
 0 s:/CN=ocsp.identrust.com/O=IDENTRUST INC/L=San Francisco/ST=California/C=US
   i:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
 1 s:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
   i:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
 2 s:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
 3 s:/O=Digital Signature Trust Co./CN=DST Root CA X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
```

For posterity, a screenshot of SSL Labs' 2016-02-20 analysis of the Identrust chain for test3:

![image](https://cloud.githubusercontent.com/assets/4592/13198863/02bca246-d7da-11e5-8c5b-282e12498e16.png)

**Comment by grandamp** [comment]
Unfortunately, I don't have a "before" screen shot of that site for this certificate path.  However, the same action may occur for the "test4" certificate path.

![symantec_trust_anchor](https://cloud.githubusercontent.com/assets/13126304/13198989/bb1b7cb2-d7e5-11e5-8e72-31dd556000f3.png)

In the event the same action occurs with the Symantec signed FBCA cert (#5), then we will know that these errors are (or are not) contributing to this behavior.

**Comment by pzb** [comment]
@grandamp I had to debug revocationcheck's download failure a few weeks ago.  Turns out it is on an IPv6-enabled host and does not fallback to IPv4 if offered an IPv6 address for the hostname but IPv6 download fails.

```
pki.treas.gov.  18000   IN  AAAA    2610:108:4000:2002::110
```

Does pki.treas.gov offer the CRL via HTTP over IPv6?

**Comment by grandamp** [comment]
Yes, suggestions?

**Comment by pzb** [comment]
@vanbroup is the author of the site.  Maybe he will know what is wrong.

**Comment by rmhrisk** [comment]
Fallback would be bad behavior, some clients can be v6 only and others v4 only. A good test of correctness would require both to work. Do we know if the v6 variant is actually available and works?

**Comment by grandamp** [comment]
For the moment, pki.treasury.gov (same IP `pki.treasury.gov.       17974   IN      CNAME   pki.treas.gov.`) listens on 443, as it is also in informational HTTP repository hosting some content.

SSLLabs tests both IPv4 and IPv6:

https://www.ssllabs.com/ssltest/analyze.html?d=pki.treasury.gov&s=2610%3a108%3a4000%3a2002%3a0%3a0%3a0%3a110&latest

But I can not confirm if there is a problem downloading the file `http://pki.treas.gov/OCIO_CA4.crl`.

**Comment by rmhrisk** [comment]
I can confirrm that the v6 address I resolve does not net me a CRL

```
Ryans-MBP:Downloads rmh$ curl -6 http://pki.treas.gov/OCIO_CA4.crl.
curl: (7) Couldn't connect to server
```

```
Ryans-MBP:Downloads rmh$ dig pki.treasury.gov AAAA

; <<>> DiG 9.8.3-P1 <<>> pki.treasury.gov AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53245
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pki.treasury.gov.      IN  AAAA

;; ANSWER SECTION:
pki.treasury.gov.   17763   IN  CNAME   pki.treas.gov.
pki.treas.gov.      18000   IN  AAAA    2610:108:4000:2002::110

;; Query time: 111 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sat Feb 20 13:45:16 2016
;; MSG SIZE  rcvd: 86

```

Based on this right now no one who is a v6 host will get a CRL and will instead rely on soft fail behavior and not see revocation results.

**Comment by grandamp** [comment]
Thank you!  And noted.  I've made a few observations that need to be
addressed.

However, does anyone believe that this _may_ have an impact on checking the
revoked certificate (from another CA)?  I'm asking in the event this issue
needs more priority.

**Comment by vanbroup** [comment]
The IPv6 connection looks to be working now for me (do you have IPv6 on your test connection @rmhrisk ?). The CRL check on revocationcheck.com is working fine now. Not sure if someone changed something on the CA side, I did not change anything on the server side at least.

```
 curl -v -o /dev/null -6 http://pki.treas.gov/OCIO_CA4.crl
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2610:108:4000:2002::110...
* Connected to pki.treas.gov (2610:108:4000:2002::110) port 80 (#0)
> GET /OCIO_CA4.crl HTTP/1.1
> User-Agent: curl/7.35.0
> Host: pki.treas.gov
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 20 Feb 2016 21:47:43 GMT
* Server IBM_HTTP_Server is not blacklisted
< Server: IBM_HTTP_Server
< Last-Modified: Sat, 20 Feb 2016 18:30:23 GMT
< ETag: "9bd5-58de04-cafc6e2d"
< Accept-Ranges: bytes
< Content-Length: 5824004
< Cache-Control: max-age=-10639
< Expires: Sat, 20 Feb 2016 18:50:23 GMT
< Content-Type: application/pkix-crl
<
```

Looking into the OCSP issue now, looks to be a bug in the ASN1 parsing for the response.

**Comment by grandamp** [comment]
Are you constantly receiving the same result?  Or, does every other request
fail?

Think load balancing.  See results of ssllabs (ipv6) for pki.treas.gov, vs
pki.treasury.gov, then look at the results via ipv4.  (Different cert).

I.e., you see a certificate behind the load balancer -vs- the other cert
(from the load balancer).

**Comment by rmhrisk** [comment]
I get the same response consistently. That said the nature of BGP makes it hard to see what is really going on from the outside.

**Comment by rmhrisk** [comment]
I should be clear, I get the same IPv6 result 100% of the time and I never get a success with curl -6. With v4 I always get the same address and curl always works.

**Comment by grandamp** [comment]
If I had IPv6 via my ISP, then I could more easily test and view through Wireshark:

```
curl -v -o /dev/null -6 http://pki.treas.gov/OCIO_CA4.crl
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2610:108:4000:2002::110...
* Immediate connect fail for 2610:108:4000:2002::110: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server`

```

That said, no changes have occurred with pki.treas[ury].gov since the time this issue was opened by me .

**Comment by vanbroup** [comment]
Currently it looks to be stable for me (while with almost 10 seconds to download the CRL it's definitely a lot slower than the IPv4 connection, OCSP doesn't seem to be fast either). Different results could indeed be caused by a BGP issue.

I can add this CRL the the distributed platform in a second so we can see how it responds from different locations in the world.

The issue with the OCSP check is resolved with a bug fix to the OCSP library. I will try to improve the system later with details about the certificate chain in the response.

**Comment by rmhrisk** [comment]
seems like this domain is not v6 ready anyway: http://ip6.nl/#!pki.treas.gov

**Comment by rmhrisk** [comment]
@vanbroup that is great, I appreciate the quick turn around!

I can confirm revocationcheck can now successfully parse the OCSP response : https://certificate.revocationcheck.com/test3.fpki.18f.gov

After the IPv6 availability issue we are discussing here are fixed (and the associated monitoring is added), there are a few other things I would change:
1. Responses are 5k+, a CA signed response is 477 bytes, most responses are under 1.5k max. 5k is a lot do all of these certs need to be returned? That's a lot of data to send if its not needed.
2. The responses are very slow for both OCSP and CRL, in some of my tests CryptoAPI would have timed out because they took so long.
3. NextUpdate is not set, it should be
4. Cache control headers are not appropriately set for OCSP or CRL responses.

**Comment by konklone** [comment]
@rmhrisk to confirm, is it the FPKI or Identrust returning the 5K responses?

**Comment by vanbroup** [comment]
@rmhrisk all good points!

I can confirm that the CRL can be downloaded over both IPv4 and IPv6 from at least my test locations in US, JP, SG, HK, DE and NL.

**Comment by rmhrisk** [comment]
treasury responses are between ~2k and 4k:

![image](https://cloud.githubusercontent.com/assets/1619279/13199608/3de982da-d7df-11e5-956e-38b98012ecf3.png)

identrus responses are 5k+:
![image](https://cloud.githubusercontent.com/assets/1619279/13199617/7eba6144-d7df-11e5-8ed1-332d6efd063c.png)

treasury CRL is big, I would be rolling the CA periodically to manage CRL size also:
![image](https://cloud.githubusercontent.com/assets/1619279/13199636/ad3b0014-d7df-11e5-91d2-5c180be65e4a.png)

**Comment by grandamp** [comment]
@rmhrisk "treasury CRL is big, I would be rolling the CA periodically to manage CRL size also". recently rolled, to which each CA signs a CRL of the same size, as each prior key.  Can you clarify how rolling the CA would lead to less revocation data?

I opened the issue as a result of testing with 2 separate browsers, using IPv4.  Does anyone have the ability to test the entire path using IPv6 exclusively?  I would be interested to see if all of the CAs in the path can be validated.

Also, a good test would be to revoke the end entity certificate. (and Eric should be able to get another...)

**Comment by konklone** [comment]
Would it be just as good to get a new cert, revoke that one, and deploy it with the same chains at different hostnames?

**Comment by konklone** [comment]
(I'd prefer to keep the behavior of the existing hostnames as consistent as possible on the server-side, to replicate the effect on existing deployed server-side certificates as closely as possible.)

**Comment by grandamp** [comment]
@eric Simply request key recovery using the same form.  Since it is a digital signature certificate, the keys are not escrowed by the CA, so you will need to provide a new key.  All other extensions remain the same. ( and increase all "OCIO CA" CRLs' size by one entry until the certificate itself, expires :/ )

**Comment by rmhrisk** [comment]
@grandamp : re: rolling: cas is a way to partition CRLs, the idea is that under normal operating conditions you issue so many certs and you revoked some percentage of them. If you roll your CA often instead of having one CRL that is very large you have many CRLs that are smaller. You pick the roll period based on your certificate issuance, revocation rate and optimal CRL size.

re ipv6, I can (manually) but I never get a connection on the v6 address for pki.treas.gov. For the v6 only test to be more useful it would be best to also:
1. configure AAAA for the domains DNS servers
2. configure v6 glue records

At least from my perspectives (http://ready.chair6.net/?url=pki.treas.gov) on the network these things have not been done yet.

**Comment by grandamp** [comment]
@rmhrisk re: rolling - Which entirely depends on the product being used as the CA, the lifetime of the certificates you issue, and the community that you cater to.

re ipv6:  If you would like to focus specifically on Treasury within this discussion, I've opened a new  issue, where the path _mostly_ relies on Treasury:   https://github.com/18F/fpki-testing/issues/3

I opened _this_ issue to point out that a certificate in the path (IdenTrust signed FBCA cert is valid by 2 separate browsers, with a revoked intermediate) .  It is still valid in those browsers.  I still have not received feedback as to if _any_ observation with the Treasury signed artifacts are leading to the lack of revocation for the Identrust signed artifact.

Does the ipv6, size of CRL & OCSP artifacts (which are all good points) contribute to this issue, or, are we identifying more _unrelated_ issues?

**Comment by rmhrisk** [comment]
@grandamp its OK. I don't actually care one way or another just trying to help figure out @konklone's original issue.

I would bet good money that his issue is the IPv6 issue were discussing. If he was on Windows I might suspect timeouts but from what I understand he is not.

Let me know if you need any help.

Ryan

**Comment by grandamp** [comment]
@rmhrisk Which issue?  Above, @konclone pointed out the SSLLabs inability to deal with OCSP responses, to which the OCSP responses from Treasury do not appear to be a problem.

I hope I have not upset or offended you, and I value your input.  I'm attempting to highlight any Treasury issue, so Treasury can resolve them effectively.

**Comment by konklone** [comment]
If I'm reading this right, it looks like we've said:
- SSL Labs indicates issues with Identrust's OCSP responder, and not anyone else's. We don't know why this is.
- Treasury may have IPv6 connectivity issues for at least some clients. @rmhrisk observes consistent failure to connect from his vantage point, and http://ready.chair6.net/?url=pki.treas.gov shows indicates a lack of IPv6 NS and glue records for pki.treas.gov. But @vanbroup can connect to Treasury over IPv6 successfully from a number of locations, so this isn't causing an issue for revocationcheck.com. We haven't evaluated its effect on other clients.
- Treasury's CRL files are on the large side (2-4KB), but this is not causing any known issue for revocationcheck.com or other clients.
- Identrust's CRL files are on the larger side (5KB), but this is also not causing any known issue for revocationcheck.com or other clients.

While we've thoroughly debugged revocationcheck.com, and identified some things Identrust and Treasury might improve on generally, I don't think we've identified why all of our Firefox instances aren't considering the certificate revoked. It could be related to the same issue SSL Labs is having, or it could be something entirely different.

**Comment by grandamp** [comment]
Or Chrome, Microsoft (browsers), and Safari! ;)

**Comment by rmhrisk** [comment]
@grandamp no no offense, I just thought we narrowed down to what the core issue was.

As I understand it this bug is about why the "test3" site is still valid in @konklone's browser.

Since browsers "soft fail" and when I use the v6 addresses I get the same behavior, my feeling is that this is very likely why @konklone is seeing this chain as valid.

As for the question of SSLLABS, I can only theorize as to what @ivanr's code is doing here but if I were asked what the problem was I would guess that it is the fact that the identrus OCSP responder returns a bag of certificates in the response vs just the responder cert. 

While it is legitimate to include more than just the responder certificate in webpki one typically either includes no certificate (ca signed responses) or just the responder certificate (ca delegate signed responses). I could believe that a test tool like SSLLABs doesn't get this right, revocationcheck.com did not.

**Comment by grandamp** [comment]
To speak to the large responses from Treasury and IdenTrust (an HID company), I believe them both to use the following product for OCSP services:  http://www.hidglobal.com/products/software/activid/activid-validation-authority

This is due to the responder including 20 pre-signed responses with each request, and not supporting a nonce.

**Comment by rmhrisk** [comment]
CertIDs are not too big, nonces would make responses not catchable.

I am on my phone right now but I suspect  the size is mostly the size of certs[].

Ryan Hurst

**Comment by rmhrisk** [comment]
I guess I wouldn't send the multiple certid responses either way since windows (and I think Firefox) won't optimize out the requests for the other certids even though it's in cache already.

**Comment by grandamp** [comment]
Yet, that is how HID/CoreStreet (a pretty big part of the OCSP responder market) works.  Axway provides a single response (Side note: but I can demonstrate availability issues with their repeater if I send a specially crafted SCVP request).  OpenCA OCSP I have slightly contributed to (SHA-2 signing support), yet I do not know whom uses it.  I'm completely incompetent when it comes to the EJBCA or Microsoft servers.  Otherwise, what are the other options?  What is a good infrastructure option with over 5M certificates in circulation, with over 300k that are revoked?

**Comment by grandamp** [comment]
BTW, if a Microsoft server encounters more than 50 OCSP responses for a given CA, it will prefer any CRL that is in the CDP extension of a given certificate.  Likewise, Microsoft has limits in CNG for how many artifacts are in a given AIA artifact (as well as a timeout, which both are configurable).

**Comment by grandamp** [comment]
Four (4) days (and counting) after the intermediate is revoked, the certificates still appear valid in both of my browsers, by way of IPv4 communications only:

Mozilla Firefox:

![image](https://cloud.githubusercontent.com/assets/13126304/13201133/7ce154f6-d832-11e5-9d81-ba5eb9de0743.png)

Google Chrome:

![screenshot_20160221-002744](https://cloud.githubusercontent.com/assets/13126304/13201140/c3e5687e-d832-11e5-9679-ece6225b7995.png)

**Comment by rmhrisk** [comment]
@grandamp re: HID/CoreStreet; I don't know of any large deployments outside the federal government using CoreStreet, though I am biased as I worked on the Valicert/Axway responder I believe it was far superior. There are a few commercial CAs still using the ValiCert/Axway product but they basically put that product on lifesupport a few years ago and I probably wouldnt consider it anymore. Several of the largest OCSP responder deployments on the internet are based on EJBCA. I would not consider OpenCA, its a hobby project at best. I personally have my own responder that I would use if it were my infrastructure, absent that the only COTS solution i would consider would be EJBCA.

re: Microsoft and OCSP, I was responsible  for the OCSP stuff at MS, so I am very familiar with the client and server behavior. I would not consider using their responder in your deployment, it was not designed for those scenarios and while changes were made to accommodate them architecturally it is not made to scale to the volumes you need, for example I would only pre-produce at this scale. As for the client behavior of switching to CRLs after it determines that it would be more efficient, yes this is a policy setting that can be configured via group policy but 50 is the default.

re: Microsoft and CNG, CNG is actually just the crypto stuff youre referring to CryptoAPI; yes, I was also a PM for CryptoAPI where all that is done, all URL retrievals are done via something called CryptNet, specifically CryptRetrieveObjectByUrl, the retrieval call is a blocking call and some responders perform very badly. As such it will "time out" in 15seconds but keep retrieving the object in the background so subsequent calls may succeed instantly even if the first call failed (the response is cached then prefetching takes over). It also limits the number of external fetches to prevent loops and DOOS like scenarios on clients.

re: the Firefox thing, I have run wireshark here on my mac and linux box and I see is a IPv6 connection to the ocsp responder being denied by the server, my assumption is the fail open behavior of clients is causing the behavior in question.

I will use my wife's Windows machine in the morning, disable IPv6 and see if I can force it to go via IPv4 and see what I see there with CAPI debugging enabled (http://unmitigatedrisk.com/?p=318) and let you know what I see..

**Comment by grandamp** [comment]
@rmhrisk You have made my day, and I have not had any sleep yet. Thank you for your tenacity, and I'd be happy to support you the _best I can_ to attain the answers that _i believe_ will benefit us all.

EJBCA has been an interest of mine for about 6 years.  (See: https://keysupport.org/)  Partially because my primary language is Java (I'm sure my repos reflect that).  But also because EJBCA gave me an opportunity to test non-compressed ECC public keys for P-384 and P-256.  For my demonstrations, I wanted to externalize OCSP from the CA, to which I used the OpenCA (at the time,the best option to me) OCSP service, because it was much easier to automate the issuance of ephemeral OCSP signing certificates.

**Comment by rmhrisk** [comment]
@grandamp My pleasure, I am happy to help if I can. I looked real briefly at Opera, Chrome, IE, Edge on my Wife's Windows 10 machine with v6 disabled show the certificate as revoked. Firefox shows the certificate as good. Debugging shows nothing odd in CryptoAPI.

I will look at the ASN.1 and the Firefox OCSP code in the AM (wife permitting).

Happy to discuss OCSP strategies with you at some point, you can contact me at rmh at unmitigatedrisk if you would like to take me up on that.

I will let you know re: firefox tomorrow.

Ryan

**Comment by ivanr** [comment]
@rmhrisk Thanks for inviting me to this thread. SSL Labs does have a OCSP response validation bug in production (yes, it's related to the bag of certificates being returned; I didn't have trust path building enabled there), but this was fixed on the dev server some time ago. I don't see any OCSP issues at the moment: https://dev.ssllabs.com/ssltest/analyze.html?d=test3.fpki.18f.gov

**Comment by konklone** [comment]
@ivanr Thank you, that's super helpful. 

It does look like there might be a different bug on dev, though? Every trust path has all intermediate certs marked as `Extra download`, even though the `test3.fpki.18f.gov` hostname supplies some of the intermediate certs directly (which SSL Labs also shows). I can see that the SHA-1 fingerprint matches between the certs shown as supplied, and the certs shown as an `Extra download`.

**Comment by konklone** [comment]
@rmhrisk @pzb @agwa @grandamp I'm not currently doing any OCSP stapling on test3.fpki.18f.gov. However, based on what I can find out (including a re-read of @agwa's [excellent writeup](https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx)) I'm still not certain of whether I can effectively staple an _intermediate_ certificate's revocation status (and/or expect clients to apply its revocation status to the validation process). 

Is this possible? If so, I will set up multiple hostnames so that one has the Identrust cross-sign cert revocation stapled and one doesn't.

**Comment by rmhrisk** [comment]
You can not. No browsers I am aware of implement multi-staple (though I have not watched that closely recently) they will rely on CRLS or CRLset like solutions for the intermediate certs in the chain. 

Ryan Hurst

**Comment by konklone** [comment]
Gotcha. I was aware no browsers supported multi-staple, but I was wondering if I could staple _only_ the intermediate's status to the connection. Sounds like no, which is what I was expecting.

**Comment by sleevi** [comment]
@konklone Correct, you cannot; Firefox would fail the connection in the latest versions (as an invalidly-signed response, since it's not for the leaf and thus has a different trust path). Chrome would fail some versions, but not others. I believe IE will ignore it (due to stapling the response to the leaf, but then not validating), and Safari will also ignore it (due to not passing stapled responses into the SecTrust API)

**Comment by grandamp** [comment]
Though I have been keeping an eye on the 2 browsers [(from the first post)](https://github.com/18F/fpki-testing/issues/2#issue-135104380), is there any value in me posting updates?  Should I expect the path to become invalid within the browser(s) at some point?

**Comment by rmhrisk** [comment]
Kai says the issue is in the unknown critical extension :

https://twitter.com/kaiengert/status/701723146546757633

What's weird is its not being rejected in the patch validation phase, will need a bit more research.

Ryan Hurst

**Comment by grandamp** [comment]
@rmhrisk Thanks for the update!  Which critical extension, in which certificate, appears to be the issue?

**Comment by grandamp** [comment]
I assume it's the [inhibitAnyPolicy (2.5.29.54)](http://www.oid-info.com/get/2.5.29.54) in the [revoked certificate](https://crt.sh/?q=58cb0063a3524c66025c69f74ebf4e401ed893a8)?

```
               SEQUENCE {
                    joint-iso-ccitt-ds.29.54 (2.5.29.54),
                    TRUE,
                    '020100'H  -- "..." --
                      ** ASN.1 data detected in previous buffer - decoding follows **
                      0
                      ** End of ASN.1 data **
                },

```

**Comment by sleevi** [comment]
@grandamp I would suggest there's no value in providing status updates for Chrome.

**Comment by grandamp** [comment]
@sleevi Thanks!  I assume Chrome on Android is quite different, but I was not certain if it's the [BC API](https://android.googlesource.com/platform/external/bouncycastle/), or something else.  Regardless, is the "issue" for Chrome on Android the same (unrecognized critical extension)?

**Comment by konklone** [comment]
@sleevi Yes, as I've stated above, and [as the Chrome team has documented](https://www.chromium.org/Home/chromium-security/crlsets), Chrome doesn't do OCSP checks in most circumstances and wouldn't be affected by Identrust's OCSP responder no matter what.

That said, a revoked intermediate with implications as broad as this one does, IMO, deserve entry into browsers' CRLsets or equivalent. I haven't yet looked up the specific revocation reason Identrust provided in their CRL, but whether it matches Chrome's automatic inclusion list or not, I would hope Chrome, Safari, and IE/Edge would all eventually ensure the cross-signature revocation is enforced.

**Comment by rmhrisk** [comment]
> I assume it's the [inhibitAnyPolicy (2.5.29.54)](http://www.oid-info.com/get/2.5.29.54) in the [revoked certificate](https://crt.sh/?q=58cb0063a3524c66025c69f74ebf4e401ed893a8)?

@grandamp yes, that would be my assumption. I will see if I can find out for sure.

**Comment by sleevi** [comment]
I don't think this bug would be best to address the systemic issues with the challenges this particular revocation represents.

For what it's worth, the responder code indicated is "cessation of operation", which is not included within CRLSets. Nor, for that matter, are CRLSets included in mobile platforms (such as Chrome on Android or Chrome on iOS). Nor, for that matter, has Identrust reported this issue to other programs nor are they presently obligated to, so it's a matter of luck or happenstance should a browser be informed of the revocation, due to non-conformance of the program requirements, and work out an appropriate revocation.

**Comment by sleevi** [comment]
@grandamp Android has never and does not presently support revocation checking.

**Comment by grandamp** [comment]
@konklone re: ["_broad implications as this one_"](https://github.com/18F/fpki-testing/issues/2#issuecomment-187371475)

For effect, it is worth noting that while this certificate was issued by a [Treasury CA](https://pki.treasury.gov/crl_certs.htm), basically any path from this trust anchor to any of the affiliates with the [Federal PKI](https://www.idmanagement.gov/IDM/s/article_content_old?tag=a0Gt0000000SfwP) will be honored as well.  [Including DoD](https://crl.gds.disa.mil/).

I'm not making any claim that that is good, or bad, however thus far [Mozilla will not distribute the Common Policy Root CA](https://bugzilla.mozilla.org/show_bug.cgi?id=478418).  ([Though it is distributed by Microsoft](http://blogs.technet.com/b/pki/archive/2011/03/13/deployment-of-the-new-federal-common-policy-ca-root-certificate.aspx))

**Comment by konklone** [comment]
> For effect, it is worth noting that while this certificate was issued by a Treasury CA, basically any path from this trust anchor to any of the affiliates with the Federal PKI will be honored as well. Including DoD.

@grandamp Yep -- this is my understanding, and why I'm glad we're all digging into this so deeply!

> For what it's worth, the responder code indicated is "cessation of operation", which is not included within CRLSets. Nor, for that matter, are CRLSets included in mobile platforms (such as Chrome on Android or Chrome on iOS). Nor, for that matter, has Identrust reported this issue to other programs nor are they presently obligated to, so it's a matter of luck or happenstance should a browser be informed of the revocation, due to non-conformance of the program requirements, and work out an appropriate revocation.

@sleevi This is a very helpful statement of the status quo, and I think we can make progress from there.

**Comment by grandamp** [comment]
@sleevi Thanks!  (I've been curious about this for some time)  It's quite hard to keep up with the "out of band" strategies for revocation checking, but I am much more interested in learning how CRLSets works.

**Comment by grandamp** [comment]
I also wanted to add a note about Chrome on my Ubuntu workstation:

Chrome Version `48.0.2564.116 (64-bit)`
Ubuntu Version `Ubuntu 14.04.4 LTS`

In all test cases, the browser does not appear to "receive" or "pay attention to" the certificate paths served by each server.  Should my configuration be "SNI" aware?

**Comment by konklone** [comment]
@grandamp That sounds like a separate issue, where your browser is caching previously seen intermediates. That happens for me as well, and makes rapid-fire browser testing of multiple hostnames difficult, when it's the same certificate with different chains. Happy to take that issue offline.

**Comment by ivanr** [comment]
@konklone There are always bugs on the dev server! Should be fixed now :)

**Comment by konklone** [comment]
@ivanr Confirmed fixed! Much obliged.

**Comment by konklone** [comment]
@grandamp @rmhrisk I think the issue is simpler than we realized -- Firefox [doesn't do any OCSP checking for intermediates](https://wiki.mozilla.org/CA:RevocationPlan), instead relying entirely on OneCRL:

> Revocation of intermediate certificates is only checked during EV validation.

I commented to this effect [on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1037590#c30).

**Comment by PaulSD** [comment]
Firefox 45.0+build2-0ubuntu0.15.10.1 seems to detect the revoked certificate if I visit test3 without ever having visited test1/2/4 ... However, once I have visited any of test1/2/4, test3 no longer shows the error:
![ff](https://cloud.githubusercontent.com/assets/74427/14158312/73648e50-f69d-11e5-9eac-2bdfb42a9b24.png)

**Comment by grandamp** [comment]
Guess OneCRL now includes the revoked cross-certificate...  

As previously mentioned, Chrome on Android thinks the path is fine.

![screenshot_20160330-175828](https://cloud.githubusercontent.com/assets/13126304/14158955/1cc9f0d6-f6a1-11e5-9677-84a164fdf1eb.png)

**Comment by grandamp** [comment]
Confirmed with:
- Firefox 44.0.2 [Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0]
- Ubuntu 14.04.4 LTS

![image](https://cloud.githubusercontent.com/assets/13126304/14159846/75048cfc-f6a6-11e5-90b3-319a6ba657f1.png)
[*]

@konklone I hate to ask, but, will this path _ever_ become "bad" according to Chrome?  To be fair, this is a pretty big difference between two commonly used browsers, to which they indicate "trust" to the person interacting with the web site.  Is there a way to raise this issue to the CA/B Forum?

*Update due to double post of the screen shot.

**Comment by sleevi** [comment]
Chrome dev here - https://www.imperialviolet.org/2014/04/29/revocationagain.html contains more details about Chrome, but for the reasons outlined, this is a different story for mobile, where bandwidth is even more precious.

The short summary is, as Adam noted, "Revocation doesn't work". You can always send messages to questions@cabforum.org (or to sleevi at google with a subject prefix of [CABFORUM], and I'll repost on your behalf), but you end up with a similar message.

**Comment by grandamp** [comment]
@sleevi I understand, and I certainly don't mean to offend.  And I agree, current means of revocation is not very scalable.

On the same Ubuntu system above, Chrome 48.0.2564.116 (Official Build) (64-bit) also shows the path as "good"/green lock.  I will assume I don't need to post a screen shot.

**Comment by sleevi** [comment]
Yes, we're aware. That's point (per-platform) is addressed by Adam's remarks about the CRLs selected and the reasons for inclusion. There's also the more pragmatic reason, which I'm still working on solving, which is due to path building idiosyncrasies across platforms (A problem unique to Chrome; Firefox as shipped by Mozilla always uses mozilla::pkix, and Windows only has to worry about CryptoAPI), revocation of certain intermediates (whether via CRL/OCSP _or_ via CRLSet) breaks path building. This was observed when Netflix and Yahoo were inaccessible in Chrome for a day, due to intermediate revocations by Symantec and Comodo (respectably).

While this bug is probably not the most fruitful to have the nuanced discussion, the post from Adam underscores why the underlying technology is fundamentally unsound at present. To this specific issue, we are aware of it, and https://bugs.chromium.org/p/chromium/issues/detail?id=589336 is tracking some of the work (but it's not being turned on until we can get consistency & testing across all platforms, due to the risks). And that doesn't address the mobile issues at all.

**Comment by konklone** [comment]
I'm asking for some confirmation from Mozilla that this got pushed out via OneCRL: https://bugzilla.mozilla.org/show_bug.cgi?id=1208264#c7

@sleevi Is there a straightforward way for us to evaluate the effects of testing out a CRLset revocation of the Identrust or Symantec FPKI cross-signs, without actually doing it? Is there a way for us to locally simulate a CRLset update? I'm willing to set up some server infrastructure and do other legwork just for that purpose, if it will give confidence to the Chrome team that such a revocation would have only the intended effects.

**Comment by sleevi** [comment]
Ish? If you're building Chromium, you can modify CertVerifyProc::Verify and the cert_verify_proc_blacklist to block. However, the built-in blacklist presently only supports SPKIs, which I don't believe is intended for this case.

Longer term, we're working with Mozilla, Microsoft, Apple, and others to improve the ability for CAs to (publicly) disclose security-relevant revocations (such as these, which are revocations of certificates capable of issuance), as well as publicly disclose all intermediates capable of issuance, such that it will be possible to test all permutations of the path graph to ensure things consistently work. That's the only means to get the full technical assurance we need.

For example, the aforementioned cases both interacted badly with whether or not clients had cached non-disclosed variants of disclosed intermediates, and the selection logic for path traversal algorithm, or the lack of a path traversal algorithm. That's why the concern over this case - especially not accidentally breaking all of the FPKI, which is an unfortunately real risk.

If it makes you feel any better (... or makes you lose sleep), don't forget that the language bindings in most server-side TLS stacks (e.g. Python, Perl, Curl, Ruby, PHP, etc) don't check revocation either, nor do they have means like OneCRL. Further emphasizing why revocation is Hard (tm).

**Comment by konklone** [comment]
OK, that's helpful to understand. To clarify, in the aforementioned cases with Symantec and Comodo, the CAs performed the revocation. Was their unilateral action sufficient to trigger the path-building fiasco you describe, or was it Chrome updating their CRLset that caused the situation?

I ask because Identrust has already unilaterally [revoked their cross-signature as of February 17th](https://bugzilla.mozilla.org/show_bug.cgi?id=1037590#c27), and I don't believe there have been any reported issues.

**Comment by sleevi** [comment]
There's no distinction between the two cases you described. A direct addition to a CRLSet vs an indirect addition to a CRLSet have the same effect with respect to path building, and behave the same as the in-code blacklist.

For a concrete example, OS X does not perform revocation checking until after it has constructed a path, and it does not construct alternative paths. If you enable revocation checking on OS X (forcing it on), and trigger the myriad ways in which the FPKI will bridge through the revoked intermediate, during revocation checking, the path will be rejected, and the connection fail. This is independent of anything in Chrome - this is strictly tied to how OS X is implemented. (iOS uses different code, FWIW).

There are many ways to trigger that behaviour, but there ARE ALSO many ways to not trigger that behaviour. However, if you're in a triggering condition, there is no way to AVOID that behavior.

Symantec was us adding them manually to the CRLSet, Comodo was simply Comodo publishing the CRL and it being picked up by the CRLSet (because Comodo made sure to publish their revocation as a security-relevant revocation we would pick up. Identrust, at last I checked, did not.)
